package servereventorganizer;

import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import server.Server;
import Accounts.Account;
import Accounts.AccountManager;
import utils.Utils;

/**
 *
 * @author pigro
 */
public class MainEventOrganizer extends javax.swing.JFrame {
        
    DefaultListModel modelLista1 = new DefaultListModel(), modelLista2 = new DefaultListModel();
    
    /**
     * Creates new form MainEventOrganizer
     */
    public MainEventOrganizer() {
        
        initComponents();
        
        Lista1.setModel(modelLista1);
        Lista2.setModel(modelLista2);
        Lista1.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent arg0) {
                if(Lista1.getSelectedValue() != null){
                    Account selectedAccount = AccountManager.getAccountByUsername(Lista1.getSelectedValue());
                    if(selectedAccount != null){
                        modelLista2.removeAllElements();
                        modelLista2.addElement(selectedAccount.getUsername());
                        modelLista2.addElement(selectedAccount.getEmail());
                        modelLista2.addElement(selectedAccount.getName());
                        modelLista2.addElement(selectedAccount.getPassword());
                        modelLista2.addElement("Amici:");
                        for(int i=0; i<selectedAccount.getAmiciArray().size(); i++)
                            modelLista2.addElement(selectedAccount.getAmiciArray().get(i).getUsername());
                        modelLista2.addElement("Richieste Da:");
                        for(int i=0; i<selectedAccount.getRichiesteDaArray().size(); i++)
                            modelLista2.addElement(selectedAccount.getRichiesteDaArray().get(i).getUsername());
                        modelLista2.addElement("Richieste A:");
                        for(int i=0; i<selectedAccount.getRichiesteAArray().size(); i++)
                            modelLista2.addElement(selectedAccount.getRichiesteAArray().get(i).getUsername());
                    }
                }
            }
        });
        
        AccountManager.loadAccountsFromFiles();
        
        /*
        Account nella = AccountManager.creaAccount(AccountManager.getNextId(), "dami.nella", "Luca Daminato", "pigro2012@gmail.com", "ciaociao");
        Account marco = AccountManager.creaAccount(AccountManager.getNextId(), "marco.dami", "Marco Daminato", "marco.dami@gmail.com", "ciaociao");
        Account flo = AccountManager.creaAccount(AccountManager.getNextId(), "flowsa", "Florian Sabani", "florian.sabani@gmail.com", "ciaociao");
        Account stecco = AccountManager.creaAccount(AccountManager.getNextId(), "andrea.dattero", "Andrea D'Attero", "andrea.dattero@gmail.com", "ciaociao");
        
        nella.addAmico(marco);
        marco.addAmico(nella);
        marco.addAmico(flo);
        nella.addRichiestaDa(flo);
        flo.addRichiestaA(nella);
        flo.addAmico(stecco);
        flo.addAmico(marco);
        stecco.addAmico(flo);
        
        AccountManager.creaAccount(AccountManager.getNextId(), "andrea.datt", "Andrea D'Attero", "andrea.datt@gmail.com", "ciaociao");
        AccountManager.creaAccount(AccountManager.getNextId(), "ariana", "Andrea ero", "andrea.datter@gmail.com", "ciaociao");
        AccountManager.creaAccount(AccountManager.getNextId(), "amianto", "Andrea Dero", "andrea.dtero@gmail.com", "ciaociao");
        AccountManager.creaAccount(AccountManager.getNextId(), "antarcite", "Andrea Attero", "andrea.tero@gmail.com", "ciaociao");
        AccountManager.creaAccount(AccountManager.getNextId(), "andrea.dao", "Andrea D", "andreattero@gmail.com", "ciaociao");
        AccountManager.creaAccount(AccountManager.getNextId(), "andrea.datte", "Andrea D'At", "andreadattero@gmail.com", "ciaociao");
        
        AccountManager.saveAccountsToFiles();
        */
        
        AggiornaButtonActionPerformed(null);
        
        Server server = new Server();
        server.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        ScrollPanel1 = new javax.swing.JScrollPane();
        Lista1 = new javax.swing.JList<>();
        ScrollPanel2 = new javax.swing.JScrollPane();
        Lista2 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        AggiornaButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Text1 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server Event Organizer");
        setBackground(new java.awt.Color(255, 255, 255));

        Lista1.setBackground(new java.awt.Color(255, 255, 255));
        Lista1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Lista1.setForeground(new java.awt.Color(0, 0, 0));
        ScrollPanel1.setViewportView(Lista1);

        Lista2.setBackground(new java.awt.Color(255, 255, 255));
        Lista2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Lista2.setForeground(new java.awt.Color(0, 0, 0));
        ScrollPanel2.setViewportView(Lista2);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        AggiornaButton.setBackground(new java.awt.Color(255, 255, 255));
        AggiornaButton.setText("Aggiorna");
        AggiornaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AggiornaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AggiornaButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(AggiornaButton)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        Text1.setForeground(new java.awt.Color(0, 0, 0));
        Text1.setText("Dettagli");
        Text1.setToolTipText("");

        Text2.setForeground(new java.awt.Color(0, 0, 0));
        Text2.setText("Users");
        Text2.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Text2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Text1)
                .addGap(332, 332, 332))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text1)
                    .addComponent(Text2))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ScrollPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ScrollPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPanel1)
                    .addComponent(ScrollPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AggiornaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AggiornaButtonActionPerformed
        modelLista1.removeAllElements();
        modelLista2.removeAllElements();
        ArrayList<Account> accounts = AccountManager.getAccounts();
        for(int i=0; i<accounts.size(); i++)
            modelLista1.addElement(accounts.get(i).getUsername());
    }//GEN-LAST:event_AggiornaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainEventOrganizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainEventOrganizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainEventOrganizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainEventOrganizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainEventOrganizer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AggiornaButton;
    private javax.swing.JList<String> Lista1;
    private javax.swing.JList<String> Lista2;
    private javax.swing.JScrollPane ScrollPanel1;
    private javax.swing.JScrollPane ScrollPanel2;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
